USE qrschools;

DROP TABLE IF EXISTS equipamentos;

CREATE TABLE equipamentos(
    id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    id_categoria INT(11) UNSIGNED NOT NULL,
    id_estado INT(11) UNSIGNED NOT NULL,
    name VARCHAR(100) NOT NULL,
    num_serie BIGINT UNSIGNED UNIQUE,
    descricao VARCHAR(355) NOT NULL,
    qrcode VARCHAR(255),
    FOREIGN KEY(id_categoria) REFERENCES equipamento_categorias(id) ON DELETE CASCADE,
    FOREIGN KEY(id_estado) REFERENCES estados(id) ON DELETE CASCADE
);

-- qrcode VARCHAR(255) NOT NULL UNIQUE

INSERT INTO equipamentos(id, id_categoria, id_estado, name, descricao, qrcode)
    VALUES
    (1, 9, 1, 'Armário Baixo-01', 'Armario descrição', NULL),
    (2, 9, 1, 'Armário Baixo-02', 'Armario descrição', NULL),
    (3, 1, 1, 'Esp32 DevKitC', 'O ESP32 DevKitC é uma placa de desenvolvimento baseada no micro controlador ESP32, que oferece conectividade Wi-Fi e Bluetooth, ideal para projetos de IoT e automação. Possui diversas interfaces como GPIO, UART, SPI e I2C, sendo compatível com Arduino, IDE, ESP-IDF e MicroPython.', NULL),
    (4, 1, 1, 'Esp32 DevKitC', 'O ESP32 DevKitC é uma placa de desenvolvimento baseada no micro controlador ESP32, que oferece conectividade Wi-Fi e Bluetooth, ideal para projetos de IoT e automação. Possui diversas interfaces como GPIO, UART, SPI e I2C, sendo compatível com Arduino, IDE, ESP-IDF e MicroPython.', NULL),
    (5, 1, 1, 'Esp32 DevKitC', 'O ESP32 DevKitC é uma placa de desenvolvimento baseada no micro controlador ESP32, que oferece conectividade Wi-Fi e Bluetooth, ideal para projetos de IoT e automação. Possui diversas interfaces como GPIO, UART, SPI e I2C, sendo compatível com Arduino, IDE, ESP-IDF e MicroPython.', NULL),
    (6, 1, 1, 'Esp32 DevKitC', 'O ESP32 DevKitC é uma placa de desenvolvimento baseada no micro controlador ESP32, que oferece conectividade Wi-Fi e Bluetooth, ideal para projetos de IoT e automação. Possui diversas interfaces como GPIO, UART, SPI e I2C, sendo compatível com Arduino, IDE, ESP-IDF e MicroPython.', NULL),
    (7, 1, 1, 'Esp32 DevKitC', 'O ESP32 DevKitC é uma placa de desenvolvimento baseada no micro controlador ESP32, que oferece conectividade Wi-Fi e Bluetooth, ideal para projetos de IoT e automação. Possui diversas interfaces como GPIO, UART, SPI e I2C, sendo compatível com Arduino, IDE, ESP-IDF e MicroPython.', NULL),
    (8, 1, 1, 'Esp32 DevKitC', 'O ESP32 DevKitC é uma placa de desenvolvimento baseada no micro controlador ESP32, que oferece conectividade Wi-Fi e Bluetooth, ideal para projetos de IoT e automação. Possui diversas interfaces como GPIO, UART, SPI e I2C, sendo compatível com Arduino, IDE, ESP-IDF e MicroPython.', NULL),
    (9, 1, 1, 'Esp32 DevKitC', 'O ESP32 DevKitC é uma placa de desenvolvimento baseada no micro controlador ESP32, que oferece conectividade Wi-Fi e Bluetooth, ideal para projetos de IoT e automação. Possui diversas interfaces como GPIO, UART, SPI e I2C, sendo compatível com Arduino, IDE, ESP-IDF e MicroPython.', NULL),
    (10, 1, 1, 'Esp32 DevKitC', 'O ESP32 DevKitC é uma placa de desenvolvimento baseada no micro controlador ESP32, que oferece conectividade Wi-Fi e Bluetooth, ideal para projetos de IoT e automação. Possui diversas interfaces como GPIO, UART, SPI e I2C, sendo compatível com Arduino, IDE, ESP-IDF e MicroPython.', NULL),
    (11, 1, 1, 'Esp32 DevKitC', 'O ESP32 DevKitC é uma placa de desenvolvimento baseada no micro controlador ESP32, que oferece conectividade Wi-Fi e Bluetooth, ideal para projetos de IoT e automação. Possui diversas interfaces como GPIO, UART, SPI e I2C, sendo compatível com Arduino, IDE, ESP-IDF e MicroPython.', NULL),
    (12, 1, 1, 'Esp32 DevKitC', 'O ESP32 DevKitC é uma placa de desenvolvimento baseada no micro controlador ESP32, que oferece conectividade Wi-Fi e Bluetooth, ideal para projetos de IoT e automação. Possui diversas interfaces como GPIO, UART, SPI e I2C, sendo compatível com Arduino, IDE, ESP-IDF e MicroPython.', NULL),
    (13, 1, 1, 'Esp32 DevKitC', 'O ESP32 DevKitC é uma placa de desenvolvimento baseada no micro controlador ESP32, que oferece conectividade Wi-Fi e Bluetooth, ideal para projetos de IoT e automação. Possui diversas interfaces como GPIO, UART, SPI e I2C, sendo compatível com Arduino, IDE, ESP-IDF e MicroPython.', NULL),
    (14, 1, 1, 'Esp32 DevKitC', 'O ESP32 DevKitC é uma placa de desenvolvimento baseada no micro controlador ESP32, que oferece conectividade Wi-Fi e Bluetooth, ideal para projetos de IoT e automação. Possui diversas interfaces como GPIO, UART, SPI e I2C, sendo compatível com Arduino, IDE, ESP-IDF e MicroPython.', NULL),
    (15, 1, 1, 'Esp32 DevKitC', 'O ESP32 DevKitC é uma placa de desenvolvimento baseada no micro controlador ESP32, que oferece conectividade Wi-Fi e Bluetooth, ideal para projetos de IoT e automação. Possui diversas interfaces como GPIO, UART, SPI e I2C, sendo compatível com Arduino, IDE, ESP-IDF e MicroPython.', NULL),
    (16, 1, 1, 'Esp32 DevKitC', 'O ESP32 DevKitC é uma placa de desenvolvimento baseada no micro controlador ESP32, que oferece conectividade Wi-Fi e Bluetooth, ideal para projetos de IoT e automação. Possui diversas interfaces como GPIO, UART, SPI e I2C, sendo compatível com Arduino, IDE, ESP-IDF e MicroPython.', NULL),
    (17, 1, 1, 'Esp32 DevKitC', 'O ESP32 DevKitC é uma placa de desenvolvimento baseada no micro controlador ESP32, que oferece conectividade Wi-Fi e Bluetooth, ideal para projetos de IoT e automação. Possui diversas interfaces como GPIO, UART, SPI e I2C, sendo compatível com Arduino, IDE, ESP-IDF e MicroPython.', NULL),
    (18, 1, 1, 'Esp32 DevKitC', 'O ESP32 DevKitC é uma placa de desenvolvimento baseada no micro controlador ESP32, que oferece conectividade Wi-Fi e Bluetooth, ideal para projetos de IoT e automação. Possui diversas interfaces como GPIO, UART, SPI e I2C, sendo compatível com Arduino, IDE, ESP-IDF e MicroPython.', NULL),
    (19, 1, 1, 'Esp32 DevKitC', 'O ESP32 DevKitC é uma placa de desenvolvimento baseada no micro controlador ESP32, que oferece conectividade Wi-Fi e Bluetooth, ideal para projetos de IoT e automação. Possui diversas interfaces como GPIO, UART, SPI e I2C, sendo compatível com Arduino, IDE, ESP-IDF e MicroPython.', NULL),
    (20, 1, 1, 'Esp32 DevKitC', 'O ESP32 DevKitC é uma placa de desenvolvimento baseada no micro controlador ESP32, que oferece conectividade Wi-Fi e Bluetooth, ideal para projetos de IoT e automação. Possui diversas interfaces como GPIO, UART, SPI e I2C, sendo compatível com Arduino, IDE, ESP-IDF e MicroPython.', NULL),
    (21, 1, 1, 'Esp32 DevKitC', 'O ESP32 DevKitC é uma placa de desenvolvimento baseada no micro controlador ESP32, que oferece conectividade Wi-Fi e Bluetooth, ideal para projetos de IoT e automação. Possui diversas interfaces como GPIO, UART, SPI e I2C, sendo compatível com Arduino, IDE, ESP-IDF e MicroPython.', NULL),
    (22, 1, 1, 'Esp32 DevKitC', 'O ESP32 DevKitC é uma placa de desenvolvimento baseada no micro controlador ESP32, que oferece conectividade Wi-Fi e Bluetooth, ideal para projetos de IoT e automação. Possui diversas interfaces como GPIO, UART, SPI e I2C, sendo compatível com Arduino, IDE, ESP-IDF e MicroPython.', NULL),
    (23, 2, 1, 'SanDisk Extreme Pro', 'O SanDisk Extreme PRO microSDXC 128 GB oferece alta velocidade de leitura (até 200 MB/s) e escrita (90 MB/s), ideal para gravação de vídeos 4K UHD e fotografia profissional. Acompanha um adaptador SD para maior compatibilidade com diversos dispositivos.', NULL),
    (24, 2, 1, 'SanDisk Extreme Pro', 'O SanDisk Extreme PRO microSDXC 128 GB oferece alta velocidade de leitura (até 200 MB/s) e escrita (90 MB/s), ideal para gravação de vídeos 4K UHD e fotografia profissional. Acompanha um adaptador SD para maior compatibilidade com diversos dispositivos.', NULL),
    (25, 2, 1, 'SanDisk Extreme Pro', 'O SanDisk Extreme PRO microSDXC 128 GB oferece alta velocidade de leitura (até 200 MB/s) e escrita (90 MB/s), ideal para gravação de vídeos 4K UHD e fotografia profissional. Acompanha um adaptador SD para maior compatibilidade com diversos dispositivos.', NULL),
    (26, 2, 1, 'SanDisk Extreme Pro', 'O SanDisk Extreme PRO microSDXC 128 GB oferece alta velocidade de leitura (até 200 MB/s) e escrita (90 MB/s), ideal para gravação de vídeos 4K UHD e fotografia profissional. Acompanha um adaptador SD para maior compatibilidade com diversos dispositivos.', NULL),
    (27, 2, 1, 'SanDisk Extreme Pro', 'O SanDisk Extreme PRO microSDXC 128 GB oferece alta velocidade de leitura (até 200 MB/s) e escrita (90 MB/s), ideal para gravação de vídeos 4K UHD e fotografia profissional. Acompanha um adaptador SD para maior compatibilidade com diversos dispositivos.', NULL),
    (28, 2, 1, 'SanDisk Extreme Pro', 'O SanDisk Extreme PRO microSDXC 128 GB oferece alta velocidade de leitura (até 200 MB/s) e escrita (90 MB/s), ideal para gravação de vídeos 4K UHD e fotografia profissional. Acompanha um adaptador SD para maior compatibilidade com diversos dispositivos.', NULL),
    (29, 2, 1, 'SanDisk Extreme Pro', 'O SanDisk Extreme PRO microSDXC 128 GB oferece alta velocidade de leitura (até 200 MB/s) e escrita (90 MB/s), ideal para gravação de vídeos 4K UHD e fotografia profissional. Acompanha um adaptador SD para maior compatibilidade com diversos dispositivos.', NULL),
    (30, 2, 1, 'SanDisk Extreme Pro', 'O SanDisk Extreme PRO microSDXC 128 GB oferece alta velocidade de leitura (até 200 MB/s) e escrita (90 MB/s), ideal para gravação de vídeos 4K UHD e fotografia profissional. Acompanha um adaptador SD para maior compatibilidade com diversos dispositivos.', NULL),
    (31, 2, 1, 'SanDisk Extreme Pro', 'O SanDisk Extreme PRO microSDXC 128 GB oferece alta velocidade de leitura (até 200 MB/s) e escrita (90 MB/s), ideal para gravação de vídeos 4K UHD e fotografia profissional. Acompanha um adaptador SD para maior compatibilidade com diversos dispositivos.', NULL),
    (32, 2, 1, 'SanDisk Extreme Pro', 'O SanDisk Extreme PRO microSDXC 128 GB oferece alta velocidade de leitura (até 200 MB/s) e escrita (90 MB/s), ideal para gravação de vídeos 4K UHD e fotografia profissional. Acompanha um adaptador SD para maior compatibilidade com diversos dispositivos.', NULL),
    (33, 2, 1, 'SanDisk Extreme Pro', 'O SanDisk Extreme PRO microSDXC 128 GB oferece alta velocidade de leitura (até 200 MB/s) e escrita (90 MB/s), ideal para gravação de vídeos 4K UHD e fotografia profissional. Acompanha um adaptador SD para maior compatibilidade com diversos dispositivos.', NULL),
    (34, 2, 1, 'SanDisk Extreme Pro', 'O SanDisk Extreme PRO microSDXC 128 GB oferece alta velocidade de leitura (até 200 MB/s) e escrita (90 MB/s), ideal para gravação de vídeos 4K UHD e fotografia profissional. Acompanha um adaptador SD para maior compatibilidade com diversos dispositivos.', NULL),
    (35, 2, 1, 'SanDisk Extreme Pro', 'O SanDisk Extreme PRO microSDXC 128 GB oferece alta velocidade de leitura (até 200 MB/s) e escrita (90 MB/s), ideal para gravação de vídeos 4K UHD e fotografia profissional. Acompanha um adaptador SD para maior compatibilidade com diversos dispositivos.', NULL),
    (36, 2, 1, 'SanDisk Extreme Pro', 'O SanDisk Extreme PRO microSDXC 128 GB oferece alta velocidade de leitura (até 200 MB/s) e escrita (90 MB/s), ideal para gravação de vídeos 4K UHD e fotografia profissional. Acompanha um adaptador SD para maior compatibilidade com diversos dispositivos.', NULL),
    (37, 2, 1, 'SanDisk Extreme Pro', 'O SanDisk Extreme PRO microSDXC 128 GB oferece alta velocidade de leitura (até 200 MB/s) e escrita (90 MB/s), ideal para gravação de vídeos 4K UHD e fotografia profissional. Acompanha um adaptador SD para maior compatibilidade com diversos dispositivos.', NULL),
    (38, 2, 1, 'SanDisk Extreme Pro', 'O SanDisk Extreme PRO microSDXC 128 GB oferece alta velocidade de leitura (até 200 MB/s) e escrita (90 MB/s), ideal para gravação de vídeos 4K UHD e fotografia profissional. Acompanha um adaptador SD para maior compatibilidade com diversos dispositivos.', NULL),
    (39, 2, 1, 'SanDisk Extreme Pro', 'O SanDisk Extreme PRO microSDXC 128 GB oferece alta velocidade de leitura (até 200 MB/s) e escrita (90 MB/s), ideal para gravação de vídeos 4K UHD e fotografia profissional. Acompanha um adaptador SD para maior compatibilidade com diversos dispositivos.', NULL),
    (40, 2, 1, 'SanDisk Extreme Pro', 'O SanDisk Extreme PRO microSDXC 128 GB oferece alta velocidade de leitura (até 200 MB/s) e escrita (90 MB/s), ideal para gravação de vídeos 4K UHD e fotografia profissional. Acompanha um adaptador SD para maior compatibilidade com diversos dispositivos.', NULL),
    (41, 2, 1, 'SanDisk Extreme Pro', 'O SanDisk Extreme PRO microSDXC 128 GB oferece alta velocidade de leitura (até 200 MB/s) e escrita (90 MB/s), ideal para gravação de vídeos 4K UHD e fotografia profissional. Acompanha um adaptador SD para maior compatibilidade com diversos dispositivos.', NULL),
    (42, 2, 1, 'SanDisk Extreme Pro', 'O SanDisk Extreme PRO microSDXC 128 GB oferece alta velocidade de leitura (até 200 MB/s) e escrita (90 MB/s), ideal para gravação de vídeos 4K UHD e fotografia profissional. Acompanha um adaptador SD para maior compatibilidade com diversos dispositivos.', NULL),
    (43, 3, 1, 'Pilha Roxa', 'Esta é uma bateria de íon de lítio 18650 com capacidade de 2500mAh e voltagem de 3,6V a 4,2V, fabricada na China. Esse tipo de bateria é comumente utilizado em lanternas, power banks, notebooks e dispositivos eletrônicos de alto desempenho.', NULL),
    (44, 3, 1, 'Pilha Roxa', 'Esta é uma bateria de íon de lítio 18650 com capacidade de 2500mAh e voltagem de 3,6V a 4,2V, fabricada na China. Esse tipo de bateria é comumente utilizado em lanternas, power banks, notebooks e dispositivos eletrônicos de alto desempenho.', NULL),
    (45, 3, 1, 'Pilha Roxa', 'Esta é uma bateria de íon de lítio 18650 com capacidade de 2500mAh e voltagem de 3,6V a 4,2V, fabricada na China. Esse tipo de bateria é comumente utilizado em lanternas, power banks, notebooks e dispositivos eletrônicos de alto desempenho.', NULL),
    (46, 3, 1, 'Pilha Roxa', 'Esta é uma bateria de íon de lítio 18650 com capacidade de 2500mAh e voltagem de 3,6V a 4,2V, fabricada na China. Esse tipo de bateria é comumente utilizado em lanternas, power banks, notebooks e dispositivos eletrônicos de alto desempenho.', NULL),
    (47, 3, 1, 'Pilha Roxa', 'Esta é uma bateria de íon de lítio 18650 com capacidade de 2500mAh e voltagem de 3,6V a 4,2V, fabricada na China. Esse tipo de bateria é comumente utilizado em lanternas, power banks, notebooks e dispositivos eletrônicos de alto desempenho.', NULL),
    (48, 3, 1, 'Pilha Roxa', 'Esta é uma bateria de íon de lítio 18650 com capacidade de 2500mAh e voltagem de 3,6V a 4,2V, fabricada na China. Esse tipo de bateria é comumente utilizado em lanternas, power banks, notebooks e dispositivos eletrônicos de alto desempenho.', NULL),
    (49, 3, 1, 'Pilha Roxa', 'Esta é uma bateria de íon de lítio 18650 com capacidade de 2500mAh e voltagem de 3,6V a 4,2V, fabricada na China. Esse tipo de bateria é comumente utilizado em lanternas, power banks, notebooks e dispositivos eletrônicos de alto desempenho.', NULL),
    (50, 3, 1, 'Pilha Roxa', 'Esta é uma bateria de íon de lítio 18650 com capacidade de 2500mAh e voltagem de 3,6V a 4,2V, fabricada na China. Esse tipo de bateria é comumente utilizado em lanternas, power banks, notebooks e dispositivos eletrônicos de alto desempenho.', NULL),
    (51, 3, 1, 'Pilha Roxa', 'Esta é uma bateria de íon de lítio 18650 com capacidade de 2500mAh e voltagem de 3,6V a 4,2V, fabricada na China. Esse tipo de bateria é comumente utilizado em lanternas, power banks, notebooks e dispositivos eletrônicos de alto desempenho.', NULL),
    (52, 3, 1, 'Pilha Roxa', 'Esta é uma bateria de íon de lítio 18650 com capacidade de 2500mAh e voltagem de 3,6V a 4,2V, fabricada na China. Esse tipo de bateria é comumente utilizado em lanternas, power banks, notebooks e dispositivos eletrônicos de alto desempenho.', NULL),
    (53, 3, 1, 'Pilha Roxa', 'Esta é uma bateria de íon de lítio 18650 com capacidade de 2500mAh e voltagem de 3,6V a 4,2V, fabricada na China. Esse tipo de bateria é comumente utilizado em lanternas, power banks, notebooks e dispositivos eletrônicos de alto desempenho.', NULL),
    (54, 3, 1, 'Pilha Roxa', 'Esta é uma bateria de íon de lítio 18650 com capacidade de 2500mAh e voltagem de 3,6V a 4,2V, fabricada na China. Esse tipo de bateria é comumente utilizado em lanternas, power banks, notebooks e dispositivos eletrônicos de alto desempenho.', NULL),
    (55, 3, 1, 'Pilha Roxa', 'Esta é uma bateria de íon de lítio 18650 com capacidade de 2500mAh e voltagem de 3,6V a 4,2V, fabricada na China. Esse tipo de bateria é comumente utilizado em lanternas, power banks, notebooks e dispositivos eletrônicos de alto desempenho.', NULL),
    (56, 3, 1, 'Pilha Roxa', 'Esta é uma bateria de íon de lítio 18650 com capacidade de 2500mAh e voltagem de 3,6V a 4,2V, fabricada na China. Esse tipo de bateria é comumente utilizado em lanternas, power banks, notebooks e dispositivos eletrônicos de alto desempenho.', NULL),
    (57, 3, 1, 'Pilha Roxa', 'Esta é uma bateria de íon de lítio 18650 com capacidade de 2500mAh e voltagem de 3,6V a 4,2V, fabricada na China. Esse tipo de bateria é comumente utilizado em lanternas, power banks, notebooks e dispositivos eletrônicos de alto desempenho.', NULL),
    (58, 3, 1, 'Pilha Roxa', 'Esta é uma bateria de íon de lítio 18650 com capacidade de 2500mAh e voltagem de 3,6V a 4,2V, fabricada na China. Esse tipo de bateria é comumente utilizado em lanternas, power banks, notebooks e dispositivos eletrônicos de alto desempenho.', NULL),
    (59, 3, 1, 'Pilha Roxa', 'Esta é uma bateria de íon de lítio 18650 com capacidade de 2500mAh e voltagem de 3,6V a 4,2V, fabricada na China. Esse tipo de bateria é comumente utilizado em lanternas, power banks, notebooks e dispositivos eletrônicos de alto desempenho.', NULL),
    (60, 3, 1, 'Pilha Roxa', 'Esta é uma bateria de íon de lítio 18650 com capacidade de 2500mAh e voltagem de 3,6V a 4,2V, fabricada na China. Esse tipo de bateria é comumente utilizado em lanternas, power banks, notebooks e dispositivos eletrônicos de alto desempenho.', NULL),
    (61, 3, 1, 'Pilha Roxa', 'Esta é uma bateria de íon de lítio 18650 com capacidade de 2500mAh e voltagem de 3,6V a 4,2V, fabricada na China. Esse tipo de bateria é comumente utilizado em lanternas, power banks, notebooks e dispositivos eletrônicos de alto desempenho.', NULL),
    (62, 3, 1, 'Pilha Roxa', 'Esta é uma bateria de íon de lítio 18650 com capacidade de 2500mAh e voltagem de 3,6V a 4,2V, fabricada na China. Esse tipo de bateria é comumente utilizado em lanternas, power banks, notebooks e dispositivos eletrônicos de alto desempenho.', NULL),
    (63, 4, 1, 'DFROBOT Study Pack of HUSKYLENS for micro:bit', 'O DFROBOT Study Pack of HUSKYLENS for micro:bit é um kit educativo que ensina reconhecimento de imagem e IA de forma prática, usando o sensor HUSKYLENS e a placa micro:bit, com tutoriais para projetos como reconhecimento facial e jogos interativos. Ideal para iniciantes em IA e robótica.', NULL),
    (64, 4, 1, 'DFROBOT Study Pack of HUSKYLENS for micro:bit', 'O DFROBOT Study Pack of HUSKYLENS for micro:bit é um kit educativo que ensina reconhecimento de imagem e IA de forma prática, usando o sensor HUSKYLENS e a placa micro:bit, com tutoriais para projetos como reconhecimento facial e jogos interativos. Ideal para iniciantes em IA e robótica.', NULL),
    (65, 4, 1, 'DFROBOT Study Pack of HUSKYLENS for micro:bit', 'O DFROBOT Study Pack of HUSKYLENS for micro:bit é um kit educativo que ensina reconhecimento de imagem e IA de forma prática, usando o sensor HUSKYLENS e a placa micro:bit, com tutoriais para projetos como reconhecimento facial e jogos interativos. Ideal para iniciantes em IA e robótica.', NULL),
    (66, 4, 1, 'DFROBOT Study Pack of HUSKYLENS for micro:bit', 'O DFROBOT Study Pack of HUSKYLENS for micro:bit é um kit educativo que ensina reconhecimento de imagem e IA de forma prática, usando o sensor HUSKYLENS e a placa micro:bit, com tutoriais para projetos como reconhecimento facial e jogos interativos. Ideal para iniciantes em IA e robótica.', NULL),
    (67, 4, 1, 'DFROBOT Study Pack of HUSKYLENS for micro:bit', 'O DFROBOT Study Pack of HUSKYLENS for micro:bit é um kit educativo que ensina reconhecimento de imagem e IA de forma prática, usando o sensor HUSKYLENS e a placa micro:bit, com tutoriais para projetos como reconhecimento facial e jogos interativos. Ideal para iniciantes em IA e robótica.', NULL),
    (68, 4, 1, 'DFROBOT Study Pack of HUSKYLENS for micro:bit', 'O DFROBOT Study Pack of HUSKYLENS for micro:bit é um kit educativo que ensina reconhecimento de imagem e IA de forma prática, usando o sensor HUSKYLENS e a placa micro:bit, com tutoriais para projetos como reconhecimento facial e jogos interativos. Ideal para iniciantes em IA e robótica.', NULL),
    (69, 4, 1, 'DFROBOT Study Pack of HUSKYLENS for micro:bit', 'O DFROBOT Study Pack of HUSKYLENS for micro:bit é um kit educativo que ensina reconhecimento de imagem e IA de forma prática, usando o sensor HUSKYLENS e a placa micro:bit, com tutoriais para projetos como reconhecimento facial e jogos interativos. Ideal para iniciantes em IA e robótica.', NULL),
    (70, 4, 1, 'DFROBOT Study Pack of HUSKYLENS for micro:bit', 'O DFROBOT Study Pack of HUSKYLENS for micro:bit é um kit educativo que ensina reconhecimento de imagem e IA de forma prática, usando o sensor HUSKYLENS e a placa micro:bit, com tutoriais para projetos como reconhecimento facial e jogos interativos. Ideal para iniciantes em IA e robótica.', NULL),
    (71, 4, 1, 'DFROBOT Study Pack of HUSKYLENS for micro:bit', 'O DFROBOT Study Pack of HUSKYLENS for micro:bit é um kit educativo que ensina reconhecimento de imagem e IA de forma prática, usando o sensor HUSKYLENS e a placa micro:bit, com tutoriais para projetos como reconhecimento facial e jogos interativos. Ideal para iniciantes em IA e robótica.', NULL),
    (72, 4, 1, 'DFROBOT Study Pack of HUSKYLENS for micro:bit', 'O DFROBOT Study Pack of HUSKYLENS for micro:bit é um kit educativo que ensina reconhecimento de imagem e IA de forma prática, usando o sensor HUSKYLENS e a placa micro:bit, com tutoriais para projetos como reconhecimento facial e jogos interativos. Ideal para iniciantes em IA e robótica.', NULL),
    (73, 4, 1, 'DFROBOT Study Pack of HUSKYLENS for micro:bit', 'O DFROBOT Study Pack of HUSKYLENS for micro:bit é um kit educativo que ensina reconhecimento de imagem e IA de forma prática, usando o sensor HUSKYLENS e a placa micro:bit, com tutoriais para projetos como reconhecimento facial e jogos interativos. Ideal para iniciantes em IA e robótica.', NULL),
    (74, 4, 1, 'DFROBOT Study Pack of HUSKYLENS for micro:bit', 'O DFROBOT Study Pack of HUSKYLENS for micro:bit é um kit educativo que ensina reconhecimento de imagem e IA de forma prática, usando o sensor HUSKYLENS e a placa micro:bit, com tutoriais para projetos como reconhecimento facial e jogos interativos. Ideal para iniciantes em IA e robótica.', NULL),
    (75, 4, 1, 'DFROBOT Study Pack of HUSKYLENS for micro:bit', 'O DFROBOT Study Pack of HUSKYLENS for micro:bit é um kit educativo que ensina reconhecimento de imagem e IA de forma prática, usando o sensor HUSKYLENS e a placa micro:bit, com tutoriais para projetos como reconhecimento facial e jogos interativos. Ideal para iniciantes em IA e robótica.', NULL),
    (76, 4, 1, 'DFROBOT Study Pack of HUSKYLENS for micro:bit', 'O DFROBOT Study Pack of HUSKYLENS for micro:bit é um kit educativo que ensina reconhecimento de imagem e IA de forma prática, usando o sensor HUSKYLENS e a placa micro:bit, com tutoriais para projetos como reconhecimento facial e jogos interativos. Ideal para iniciantes em IA e robótica.', NULL),
    (77, 4, 1, 'DFROBOT Study Pack of HUSKYLENS for micro:bit', 'O DFROBOT Study Pack of HUSKYLENS for micro:bit é um kit educativo que ensina reconhecimento de imagem e IA de forma prática, usando o sensor HUSKYLENS e a placa micro:bit, com tutoriais para projetos como reconhecimento facial e jogos interativos. Ideal para iniciantes em IA e robótica.', NULL),
    (78, 4, 1, 'DFROBOT Study Pack of HUSKYLENS for micro:bit', 'O DFROBOT Study Pack of HUSKYLENS for micro:bit é um kit educativo que ensina reconhecimento de imagem e IA de forma prática, usando o sensor HUSKYLENS e a placa micro:bit, com tutoriais para projetos como reconhecimento facial e jogos interativos. Ideal para iniciantes em IA e robótica.', NULL),
    (79, 4, 1, 'DFROBOT Study Pack of HUSKYLENS for micro:bit', 'O DFROBOT Study Pack of HUSKYLENS for micro:bit é um kit educativo que ensina reconhecimento de imagem e IA de forma prática, usando o sensor HUSKYLENS e a placa micro:bit, com tutoriais para projetos como reconhecimento facial e jogos interativos. Ideal para iniciantes em IA e robótica.', NULL),
    (80, 4, 1, 'DFROBOT Study Pack of HUSKYLENS for micro:bit', 'O DFROBOT Study Pack of HUSKYLENS for micro:bit é um kit educativo que ensina reconhecimento de imagem e IA de forma prática, usando o sensor HUSKYLENS e a placa micro:bit, com tutoriais para projetos como reconhecimento facial e jogos interativos. Ideal para iniciantes em IA e robótica.', NULL),
    (81, 4, 1, 'DFROBOT Study Pack of HUSKYLENS for micro:bit', 'O DFROBOT Study Pack of HUSKYLENS for micro:bit é um kit educativo que ensina reconhecimento de imagem e IA de forma prática, usando o sensor HUSKYLENS e a placa micro:bit, com tutoriais para projetos como reconhecimento facial e jogos interativos. Ideal para iniciantes em IA e robótica.', NULL),
    (82, 4, 1, 'DFROBOT Study Pack of HUSKYLENS for micro:bit', 'O DFROBOT Study Pack of HUSKYLENS for micro:bit é um kit educativo que ensina reconhecimento de imagem e IA de forma prática, usando o sensor HUSKYLENS e a placa micro:bit, com tutoriais para projetos como reconhecimento facial e jogos interativos. Ideal para iniciantes em IA e robótica.', NULL),
    (83, 4, 1, 'Micro:Maqueen Plus V2', 'O Micro:Maqueen Plus V2 é um robô educacional avançado compatível com micro:bit, projetado para ensinar programação, robótica e STEM de forma interativa, com suporte a bateria 18650 para maior autonomia. Ideal para estudantes e entusiastas que querem explorar sensores, motores e lógica de programação em projetos práticos.', NULL),
    (84, 4, 1, 'Micro:Maqueen Plus V2', 'O Micro:Maqueen Plus V2 é um robô educacional avançado compatível com micro:bit, projetado para ensinar programação, robótica e STEM de forma interativa, com suporte a bateria 18650 para maior autonomia. Ideal para estudantes e entusiastas que querem explorar sensores, motores e lógica de programação em projetos práticos.', NULL),
    (85, 4, 1, 'Micro:Maqueen Plus V2', 'O Micro:Maqueen Plus V2 é um robô educacional avançado compatível com micro:bit, projetado para ensinar programação, robótica e STEM de forma interativa, com suporte a bateria 18650 para maior autonomia. Ideal para estudantes e entusiastas que querem explorar sensores, motores e lógica de programação em projetos práticos.', NULL),
    (86, 4, 1, 'Micro:Maqueen Plus V2', 'O Micro:Maqueen Plus V2 é um robô educacional avançado compatível com micro:bit, projetado para ensinar programação, robótica e STEM de forma interativa, com suporte a bateria 18650 para maior autonomia. Ideal para estudantes e entusiastas que querem explorar sensores, motores e lógica de programação em projetos práticos.', NULL),
    (87, 4, 1, 'Micro:Maqueen Plus V2', 'O Micro:Maqueen Plus V2 é um robô educacional avançado compatível com micro:bit, projetado para ensinar programação, robótica e STEM de forma interativa, com suporte a bateria 18650 para maior autonomia. Ideal para estudantes e entusiastas que querem explorar sensores, motores e lógica de programação em projetos práticos.', NULL),
    (88, 4, 1, 'Micro:Maqueen Plus V2', 'O Micro:Maqueen Plus V2 é um robô educacional avançado compatível com micro:bit, projetado para ensinar programação, robótica e STEM de forma interativa, com suporte a bateria 18650 para maior autonomia. Ideal para estudantes e entusiastas que querem explorar sensores, motores e lógica de programação em projetos práticos.', NULL),
    (89, 4, 1, 'Micro:Maqueen Plus V2', 'O Micro:Maqueen Plus V2 é um robô educacional avançado compatível com micro:bit, projetado para ensinar programação, robótica e STEM de forma interativa, com suporte a bateria 18650 para maior autonomia. Ideal para estudantes e entusiastas que querem explorar sensores, motores e lógica de programação em projetos práticos.', NULL),
    (90, 4, 1, 'Micro:Maqueen Plus V2', 'O Micro:Maqueen Plus V2 é um robô educacional avançado compatível com micro:bit, projetado para ensinar programação, robótica e STEM de forma interativa, com suporte a bateria 18650 para maior autonomia. Ideal para estudantes e entusiastas que querem explorar sensores, motores e lógica de programação em projetos práticos.', NULL),
    (91, 4, 1, 'Micro:Maqueen Plus V2', 'O Micro:Maqueen Plus V2 é um robô educacional avançado compatível com micro:bit, projetado para ensinar programação, robótica e STEM de forma interativa, com suporte a bateria 18650 para maior autonomia. Ideal para estudantes e entusiastas que querem explorar sensores, motores e lógica de programação em projetos práticos.', NULL),
    (92, 4, 1, 'Micro:Maqueen Plus V2', 'O Micro:Maqueen Plus V2 é um robô educacional avançado compatível com micro:bit, projetado para ensinar programação, robótica e STEM de forma interativa, com suporte a bateria 18650 para maior autonomia. Ideal para estudantes e entusiastas que querem explorar sensores, motores e lógica de programação em projetos práticos.', NULL),
    (93, 4, 1, 'Micro:Maqueen Plus V2', 'O Micro:Maqueen Plus V2 é um robô educacional avançado compatível com micro:bit, projetado para ensinar programação, robótica e STEM de forma interativa, com suporte a bateria 18650 para maior autonomia. Ideal para estudantes e entusiastas que querem explorar sensores, motores e lógica de programação em projetos práticos.', NULL),
    (94, 4, 1, 'Micro:Maqueen Plus V2', 'O Micro:Maqueen Plus V2 é um robô educacional avançado compatível com micro:bit, projetado para ensinar programação, robótica e STEM de forma interativa, com suporte a bateria 18650 para maior autonomia. Ideal para estudantes e entusiastas que querem explorar sensores, motores e lógica de programação em projetos práticos.', NULL),
    (95, 4, 1, 'Micro:Maqueen Plus V2', 'O Micro:Maqueen Plus V2 é um robô educacional avançado compatível com micro:bit, projetado para ensinar programação, robótica e STEM de forma interativa, com suporte a bateria 18650 para maior autonomia. Ideal para estudantes e entusiastas que querem explorar sensores, motores e lógica de programação em projetos práticos.', NULL),
    (96, 4, 1, 'Micro:Maqueen Plus V2', 'O Micro:Maqueen Plus V2 é um robô educacional avançado compatível com micro:bit, projetado para ensinar programação, robótica e STEM de forma interativa, com suporte a bateria 18650 para maior autonomia. Ideal para estudantes e entusiastas que querem explorar sensores, motores e lógica de programação em projetos práticos.', NULL),
    (97, 4, 1, 'Micro:Maqueen Plus V2', 'O Micro:Maqueen Plus V2 é um robô educacional avançado compatível com micro:bit, projetado para ensinar programação, robótica e STEM de forma interativa, com suporte a bateria 18650 para maior autonomia. Ideal para estudantes e entusiastas que querem explorar sensores, motores e lógica de programação em projetos práticos.', NULL),
    (98, 4, 1, 'Micro:Maqueen Plus V2', 'O Micro:Maqueen Plus V2 é um robô educacional avançado compatível com micro:bit, projetado para ensinar programação, robótica e STEM de forma interativa, com suporte a bateria 18650 para maior autonomia. Ideal para estudantes e entusiastas que querem explorar sensores, motores e lógica de programação em projetos práticos.', NULL),
    (99, 5, 1, 'Huskylens', 'O Huskylens é um sensor de visão com IA plug-and-play que simplifica projetos de reconhecimento facial, de objetos e cores, ideal para educação e protótipos em robótica.', NULL),
    (100, 5, 1, 'Huskylens', 'O Huskylens é um sensor de visão com IA plug-and-play que simplifica projetos de reconhecimento facial, de objetos e cores, ideal para educação e protótipos em robótica.', NULL),
    (101, 5, 1, 'Huskylens', 'O Huskylens é um sensor de visão com IA plug-and-play que simplifica projetos de reconhecimento facial, de objetos e cores, ideal para educação e protótipos em robótica.', NULL),
    (102, 5, 1, 'Huskylens', 'O Huskylens é um sensor de visão com IA plug-and-play que simplifica projetos de reconhecimento facial, de objetos e cores, ideal para educação e protótipos em robótica.', NULL),
    (103, 5, 1, 'Huskylens', 'O Huskylens é um sensor de visão com IA plug-and-play que simplifica projetos de reconhecimento facial, de objetos e cores, ideal para educação e protótipos em robótica.', NULL),
    (104, 5, 1, 'Huskylens', 'O Huskylens é um sensor de visão com IA plug-and-play que simplifica projetos de reconhecimento facial, de objetos e cores, ideal para educação e protótipos em robótica.', NULL),
    (105, 5, 1, 'Huskylens', 'O Huskylens é um sensor de visão com IA plug-and-play que simplifica projetos de reconhecimento facial, de objetos e cores, ideal para educação e protótipos em robótica.', NULL),
    (106, 5, 1, 'Huskylens', 'O Huskylens é um sensor de visão com IA plug-and-play que simplifica projetos de reconhecimento facial, de objetos e cores, ideal para educação e protótipos em robótica.', NULL),
    (107, 5, 1, 'Huskylens', 'O Huskylens é um sensor de visão com IA plug-and-play que simplifica projetos de reconhecimento facial, de objetos e cores, ideal para educação e protótipos em robótica.', NULL),
    (108, 5, 1, 'Huskylens', 'O Huskylens é um sensor de visão com IA plug-and-play que simplifica projetos de reconhecimento facial, de objetos e cores, ideal para educação e protótipos em robótica.', NULL),
    (109, 5, 1, 'Huskylens', 'O Huskylens é um sensor de visão com IA plug-and-play que simplifica projetos de reconhecimento facial, de objetos e cores, ideal para educação e protótipos em robótica.', NULL),
    (110, 5, 1, 'Huskylens', 'O Huskylens é um sensor de visão com IA plug-and-play que simplifica projetos de reconhecimento facial, de objetos e cores, ideal para educação e protótipos em robótica.', NULL),
    (111, 5, 1, 'Huskylens', 'O Huskylens é um sensor de visão com IA plug-and-play que simplifica projetos de reconhecimento facial, de objetos e cores, ideal para educação e protótipos em robótica.', NULL),
    (112, 5, 1, 'Huskylens', 'O Huskylens é um sensor de visão com IA plug-and-play que simplifica projetos de reconhecimento facial, de objetos e cores, ideal para educação e protótipos em robótica.', NULL),
    (113, 5, 1, 'Huskylens', 'O Huskylens é um sensor de visão com IA plug-and-play que simplifica projetos de reconhecimento facial, de objetos e cores, ideal para educação e protótipos em robótica.', NULL),
    (114, 5, 1, 'Huskylens', 'O Huskylens é um sensor de visão com IA plug-and-play que simplifica projetos de reconhecimento facial, de objetos e cores, ideal para educação e protótipos em robótica.', NULL),
    (115, 5, 1, 'Huskylens', 'O Huskylens é um sensor de visão com IA plug-and-play que simplifica projetos de reconhecimento facial, de objetos e cores, ideal para educação e protótipos em robótica.', NULL),
    (116, 5, 1, 'Huskylens', 'O Huskylens é um sensor de visão com IA plug-and-play que simplifica projetos de reconhecimento facial, de objetos e cores, ideal para educação e protótipos em robótica.', NULL),
    (117, 5, 1, 'Huskylens', 'O Huskylens é um sensor de visão com IA plug-and-play que simplifica projetos de reconhecimento facial, de objetos e cores, ideal para educação e protótipos em robótica.', NULL),
    (118, 5, 1, 'Huskylens', 'O Huskylens é um sensor de visão com IA plug-and-play que simplifica projetos de reconhecimento facial, de objetos e cores, ideal para educação e protótipos em robótica.', NULL),
    (119, 4, 1, 'Micro:Maqueen Plus V2', 'O Micro:Maqueen Plus V2 é um robô educacional avançado compatível com micro:bit, projetado para ensinar programação, robótica e STEM de forma interativa, com suporte a bateria 18650 para maior autonomia. Ideal para estudantes e entusiastas que querem explorar sensores, motores e lógica de programação em projetos práticos.', NULL),
    (120, 4, 1, 'Micro:Maqueen Plus V2', 'O Micro:Maqueen Plus V2 é um robô educacional avançado compatível com micro:bit, projetado para ensinar programação, robótica e STEM de forma interativa, com suporte a bateria 18650 para maior autonomia. Ideal para estudantes e entusiastas que querem explorar sensores, motores e lógica de programação em projetos práticos.', NULL),
    (121, 4, 1, 'Micro:Maqueen Plus V2', 'O Micro:Maqueen Plus V2 é um robô educacional avançado compatível com micro:bit, projetado para ensinar programação, robótica e STEM de forma interativa, com suporte a bateria 18650 para maior autonomia. Ideal para estudantes e entusiastas que querem explorar sensores, motores e lógica de programação em projetos práticos.', NULL),
    (122, 4, 1, 'Micro:Maqueen Plus V2', 'O Micro:Maqueen Plus V2 é um robô educacional avançado compatível com micro:bit, projetado para ensinar programação, robótica e STEM de forma interativa, com suporte a bateria 18650 para maior autonomia. Ideal para estudantes e entusiastas que querem explorar sensores, motores e lógica de programação em projetos práticos.', NULL),
    (123, 6, 1, 'Seeed Studio XIAO SAMD21', 'O Seeed Studio XIAO SAMD21 é um microcontrolador compacto e poderoso baseado no ARM Cortex-M0+, ideal para prototipagem e projetos IoT, com compatibilidade Arduino e um curso gratuito para iniciantes.', NULL),
    (124, 6, 1, 'Seeed Studio XIAO SAMD21', 'O Seeed Studio XIAO SAMD21 é um microcontrolador compacto e poderoso baseado no ARM Cortex-M0+, ideal para prototipagem e projetos IoT, com compatibilidade Arduino e um curso gratuito para iniciantes.', NULL),
    (125, 6, 1, 'Seeed Studio XIAO SAMD21', 'O Seeed Studio XIAO SAMD21 é um microcontrolador compacto e poderoso baseado no ARM Cortex-M0+, ideal para prototipagem e projetos IoT, com compatibilidade Arduino e um curso gratuito para iniciantes.', NULL),
    (126, 6, 1, 'Seeed Studio XIAO SAMD21', 'O Seeed Studio XIAO SAMD21 é um microcontrolador compacto e poderoso baseado no ARM Cortex-M0+, ideal para prototipagem e projetos IoT, com compatibilidade Arduino e um curso gratuito para iniciantes.', NULL),
    (127, 7, 1, 'T-Display-S3', 'O T-Display-S3 é uma placa de desenvolvimento com tela LCD integrada, baseada no ESP32-S3, perfeita para projetos IoT, interfaces gráficas e protótipos com visualização instantânea.', NULL),
    (128, 7, 1, 'T-Display-S3', 'O T-Display-S3 é uma placa de desenvolvimento com tela LCD integrada, baseada no ESP32-S3, perfeita para projetos IoT, interfaces gráficas e protótipos com visualização instantânea.', NULL),
    (129, 8, 1, 'Capa de porteção', 'Capa de proteção para o T-Display-S3', NULL),
    (130, 8, 1, 'Capa de porteção', 'Capa de proteção para o T-Display-S3', NULL),
    (131, 8, 1, 'Capa de porteção', 'Capa de proteção para o T-Display-S3', NULL),
    (132, 8, 1, 'Capa de porteção', 'Capa de proteção para o T-Display-S3', NULL),
    (133, 8, 1, 'Capa de porteção', 'Capa de proteção para o T-Display-S3', NULL),
    (134, 8, 1, 'Capa de porteção', 'Capa de proteção para o T-Display-S3', NULL);

INSERT INTO equipamentos(id_categoria, id_estado, nome, descricao, qrcode)
    VALUES
    ('Bloom mini', NULL, 'Mesa', 'Estrutura com pé central com base circular no topo', 'qrcode mesaNULL'),
    ('Block retangular',NULL, 'Sofá', 'Módulo com espuma revestido com semi-pele verde', 'qrcode sofaNULL'),
    ('Block retangular',NULL, 'Sofá', 'Módulo com espuma revestido com semi-pele verde', 'qrcode sofaNULL'),
    ('Mesa Rebatível',NULL, 'Mesa', 'Estrutura metálica com um sistema manual de rebatimento', 'qrcode mesa'),
    ('Mesa Rebatível',NULL, 'Mesa', 'Estrutura metálica com um sistema manual de rebatimento', 'qrcode mesa'),
    ('Mesa Rebatível',NULL, 'Mesa', 'Estrutura metálica com um sistema manual de rebatimento', 'qrcode mesa'),
    ('Mesa Rebatível',NULL, 'Mesa', 'Estrutura metálica com um sistema manual de rebatimento', 'qrcode mesa'),
    ('Mesa Rebatível',NULL, 'Mesa', 'Estrutura metálica com um sistema manual de rebatimento', 'qrcode mesa'),
    ('Mesa Rebatível',NULL, 'Mesa', 'Estrutura metálica com um sistema manual de rebatimento', 'qrcode mesa'),
    ('Mesa Rebatível',NULL, 'Mesa', 'Estrutura metálica com um sistema manual de rebatimento', 'qrcode mesa'),
    ('Mesa Rebatível',NULL, 'Mesa', 'Estrutura metálica com um sistema manual de rebatimento', 'qrcode mesa'),
    ('Mesa Rebatível',NULL, 'Mesa', 'Estrutura metálica com um sistema manual de rebatimento', 'qrcode mesa'),
    ('Mesa Rebatível',NULL, 'Mesa', 'Estrutura metálica com um sistema manual de rebatimento', 'qrcode mesa'),
    ('Mesa Rebatível',NULL, 'Mesa', 'Estrutura metálica com um sistema manual de rebatimento', 'qrcode mesa'),
    ('Mesa Rebatível',NULL, 'Mesa', 'Estrutura metálica com um sistema manual de rebatimento', 'qrcode mesa'),
    ('Desk 21 Professor',NULL, 'Mesa', 'Estrutura metálica', 'qrcode mesa'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira preta', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira preta', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira preta', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira preta', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira preta', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira preta', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira preta', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira preta', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira preta', 'qrcode cadeira'),

    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Team dupla',NULL, 'Mesa', 'Estrutura metálica', 'qrcode mesa'),
    ('Team dupla',NULL, 'Mesa', 'Estrutura metálica', 'qrcode mesa'),
    ('Team dupla',NULL, 'Mesa', 'Estrutura metálica', 'qrcode mesa'),
    ('Team dupla',NULL, 'Mesa', 'Estrutura metálica', 'qrcode mesa'),
    ('Team dupla',NULL, 'Mesa', 'Estrutura metálica', 'qrcode mesa'),
    ('Team dupla',NULL, 'Mesa', 'Estrutura metálica', 'qrcode mesa'),
    ('Team dupla',NULL, 'Mesa', 'Estrutura metálica', 'qrcode mesa'),
    ('Team dupla',NULL, 'Mesa', 'Estrutura metálica', 'qrcode mesa'),
    ('Team dupla',NULL, 'Mesa', 'Estrutura metálica', 'qrcode mesa'),
    ('Team dupla',NULL, 'Mesa', 'Estrutura metálica', 'qrcode mesa'),
    ('Team dupla',NULL, 'Mesa', 'Estrutura metálica', 'qrcode mesa'),
    ('Team dupla',NULL, 'Mesa', 'Estrutura metálica', 'qrcode mesa'),
    ('Team dupla',NULL, 'Mesa', 'Estrutura metálica', 'qrcode mesa'),
    ('Desk 21 Professor',NULL, 'Mesa', 'Estrutura metálica', 'qrcode mesa'),

    ('Mesa Rebatível',NULL, 'Mesa', 'Estrutura metálica com um sistema manual de rebatimento', 'qrcode mesa'),
    ('Mesa Rebatível',NULL, 'Mesa', 'Estrutura metálica com um sistema manual de rebatimento', 'qrcode mesa'),
    ('Mesa Rebatível',NULL, 'Mesa', 'Estrutura metálica com um sistema manual de rebatimento', 'qrcode mesa'),
    ('Mesa Rebatível',NULL, 'Mesa', 'Estrutura metálica com um sistema manual de rebatimento', 'qrcode mesa'),
    ('Mesa Rebatível',NULL, 'Mesa', 'Estrutura metálica com um sistema manual de rebatimento', 'qrcode mesa'),
    ('Mesa Rebatível',NULL, 'Mesa', 'Estrutura metálica com um sistema manual de rebatimento', 'qrcode mesa'),
    ('Mesa Rebatível',NULL, 'Mesa', 'Estrutura metálica com um sistema manual de rebatimento', 'qrcode mesa'),
    ('Mesa Rebatível',NULL, 'Mesa', 'Estrutura metálica com um sistema manual de rebatimento', 'qrcode mesa'),
    ('Mesa Rebatível',NULL, 'Mesa', 'Estrutura metálica com um sistema manual de rebatimento', 'qrcode mesa'),
    ('Mesa Rebatível',NULL, 'Mesa', 'Estrutura metálica com um sistema manual de rebatimento', 'qrcode mesa'),
    ('Mesa Rebatível',NULL, 'Mesa', 'Estrutura metálica com um sistema manual de rebatimento', 'qrcode mesa'),
    ('Mesa Rebatível',NULL, 'Mesa', 'Estrutura metálica com um sistema manual de rebatimento', 'qrcode mesa'),
    ('Bancada simples',NULL, 'Mesa', 'Estrutura metálica desmontável', 'qrcode mesa'),
    ('Ergos alta',NULL, 'Cadeira', 'Cadeira alta cinzenta', 'qrcode cadeira'),
    ('Ergos alta',NULL, 'Cadeira', 'Cadeira alta cinzenta', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira preta', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira preta', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira preta', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira preta', 'qrcode cadeira'),

    ('Bancada simples',NULL, 'Mesa', 'Estrutura metálica desmontável', 'qrcode mesa'),
    ('Bancada simples',NULL, 'Mesa', 'Estrutura metálica desmontável', 'qrcode mesa'),
    ('Ergos alta',NULL, 'Cadeira', 'Cadeira alta azul', 'qrcode cadeira'),
    ('Ergos alta',NULL, 'Cadeira', 'Cadeira alta azul', 'qrcode cadeira'),
    ('Ergos alta',NULL, 'Cadeira', 'Cadeira alta cinzenta', 'qrcode cadeira'),
    ('Ergos alta',NULL, 'Cadeira', 'Cadeira alta cinzenta', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira vermelha', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira vermelha', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira vermelha', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira vermelha', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira vermelha', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira vermelha', 'qrcode cadeira'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa vermelha', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa vermelha', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa vermelha', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa vermelha', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa vermelha', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa vermelha', 'qrcode mesa'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa azul', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa azul', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa azul', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa azul', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa azul', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa azul', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa azul', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa azul', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa azul', 'qrcode mesa'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa verde', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa verde', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa verde', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa verde', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa verde', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa verde', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa verde', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa verde', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa verde', 'qrcode mesa'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira amarela', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira amarela', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira amarela', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira amarela', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira amarela', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira amarela', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira amarela', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira amarela', 'qrcode cadeira'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa amarela', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa amarela', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa amarela', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa amarela', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa amarela', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa amarela', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa amarela', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa amarela', 'qrcode mesa'),
    ('Desk 21 Professor',NULL, 'Mesa', 'Estrutura metálica', 'qrcode mesa'),

    ('Bancada simples',NULL, 'Mesa', 'Estrutura metálica desmontável', 'qrcode mesa'),
    ('Ergos alta',NULL, 'Cadeira', 'Cadeira alta cinzenta', 'qrcode cadeira'),
    ('Ergos alta',NULL, 'Cadeira', 'Cadeira alta cinzenta', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira amarela', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira amarela', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira amarela', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira amarela', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira amarela', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira vermelha', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira vermelha', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira vermelha', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira vermelha', 'qrcode cadeira'),
    ('Desk 21 Professor',NULL, 'Mesa', 'Estrutura metálica', 'qrcode mesa'),
    ('Team dupla',NULL, 'Mesa', 'Estrutura metálica', 'qrcode mesa'),
    ('Team dupla',NULL, 'Mesa', 'Estrutura metálica', 'qrcode mesa'),
    ('Team dupla',NULL, 'Mesa', 'Estrutura metálica', 'qrcode mesa'),
    ('Team dupla',NULL, 'Mesa', 'Estrutura metálica', 'qrcode mesa'),
    ('Team dupla',NULL, 'Mesa', 'Estrutura metálica', 'qrcode mesa'),
    ('Team dupla',NULL, 'Mesa', 'Estrutura metálica', 'qrcode mesa'),
    ('Team dupla',NULL, 'Mesa', 'Estrutura metálica', 'qrcode mesa'),
    ('Team dupla',NULL, 'Mesa', 'Estrutura metálica', 'qrcode mesa'),
    ('Team dupla',NULL, 'Mesa', 'Estrutura metálica', 'qrcode mesa'),
    ('Team dupla',NULL, 'Mesa', 'Estrutura metálica', 'qrcode mesa'),
    ('Team dupla',NULL, 'Mesa', 'Estrutura metálica', 'qrcode mesa'),
    ('Team dupla',NULL, 'Mesa', 'Estrutura metálica', 'qrcode mesa'),
    ('Team dupla',NULL, 'Mesa', 'Estrutura metálica', 'qrcode mesa'),

    ('Ergos edge',NULL, 'Mesa', 'Mesa vermelha', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa vermelha', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa vermelha', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa vermelha', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa vermelha', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa vermelha', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa vermelha', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa vermelha', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa vermelha', 'qrcode mesa'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira vermelha', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira vermelha', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira vermelha', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira vermelha', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira vermelha', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira vermelha', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira vermelha', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira vermelha', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira vermelha', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira vermelha', 'qrcode cadeira'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa amarela', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa amarela', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa amarela', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa amarela', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa amarela', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa amarela', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa amarela', 'qrcode mesa'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira amarela', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira amarela', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira amarela', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira amarela', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira amarela', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira amarela', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira amarela', 'qrcode cadeira'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa azul', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa azul', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa azul', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa azul', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa azul', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa azul', 'qrcode mesa'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira azul', 'qrcode cadeira'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa verde', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa verde', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa verde', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa verde', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa verde', 'qrcode mesa'),
    ('Ergos edge',NULL, 'Mesa', 'Mesa verde', 'qrcode mesa'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Ergos one',NULL, 'Cadeira', 'Cadeira verde', 'qrcode cadeira'),
    ('Desk 21 Professor',NULL, 'Mesa', 'Estrutura metálica', 'qrcode mesa'),
    ('Bancada simples',NULL, 'Mesa', 'Estrutura metálica desmontável', 'qrcode mesa'),
    ('Bancada simples',NULL, 'Mesa', 'Estrutura metálica desmontável', 'qrcode mesa'),
    ('Ergos alta',NULL, 'Cadeira', 'Cadeira alta azul', 'qrcode cadeira'),
    ('Ergos alta',NULL, 'Cadeira', 'Cadeira alta azul', 'qrcode cadeira'),
    ('Ergos alta',NULL, 'Cadeira', 'Cadeira alta azul', 'qrcode cadeira'),
    ('Ergos alta',NULL, 'Cadeira', 'Cadeira alta azul', 'qrcode cadeira');